# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6664f51c9adf14538553b5055ca2d75da5c764c6107af200b0404a940ea20c70c01b5a3485ea55cfc83aee502484433fc32be704bc01e5c34557759573df47a4

test:
  secret_key_base: 05a0e57b0fe2819dd821155c3ceb678c4d6b10f67cf747d81d0f6f5a18053c6d69072f87459d334216e2f13cf8df67aa2fb93679ffb2a9d5230b884628c08791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
